// src/constants/systemKey.js

/**
 * Định nghĩa các hằng số (constants) để lấy SystemKey.
 * Code khớp `codeValue` parent từ GET /api/SystemKey.
 */
export const SYSTEM_KEY = {
  STATUS: 'STATUS',
  ROLE: 'ROLE',
  GENDER: 'GENDER',
  CROP_TYPE: 'CROP_TYPE',
  CROP_STATUS: 'CROP_STATUS',
  CROP_PROCESS: 'CROP_PROCESS',
  FERTILIZER_UNIT: 'FERTILIZER_UNIT',
  PESTICIDE_UNIT: 'PESTICIDE_UNIT',
  COMPONENT_UNIT: 'COMPONENT_UNIT',
  AREA_UNIT: 'AREA_UNIT',
  FERTILIZER_TYPE: 'FERTILIZER_TYPE',

  // Cultivation / main flow statuses (SystemKey groups)
  LOGBOOK_STATUS: 'LOGBOOK_STATUS',
  REVIEW_STATUS: 'REVIEW_STATUS',
  CULTIVATION_STAGE_STATUS: 'CULTIVATION_STAGE_STATUS',
  WORK_TASK_STATUS: 'WORK_TASK_STATUS',
  APPROVAL_STATUS: 'APPROVAL_STATUS',
  HARVEST_BATCH_STATUS: 'HARVEST_BATCH_STATUS',
  QR_STATUS: 'QR_STATUS',
  LAND_PLOT_STATUS: 'LAND_PLOT_STATUS',
  EQUIPMENT_STATUS: 'EQUIPMENT_STATUS',
}
