// Mock data cho Production Plans (Kế hoạch sản xuất)
export const MOCK_PRODUCTION_PLANS = [
  {
    id: 'PP-001',
    name: 'Vụ Lúa Xuân 2026 - Khu A',
    crop: 'Lúa Jasmine',
    category: 'Lúa nước',
    specificCrop: 'Jasmine 85',
    area: 'Khu A - Đồng ruộng phía Bắc',
    supervisor: {
      name: 'Nguyễn Văn An',
      avatarColor: 'bg-blue-500',
    },
    supervisorId: 'user-001',
    startDate: '2026-02-15',
    expectedStartDate: '2026-02-15',
    isPlanned: false,
    status: true,
    createdAt: '2026-01-20',
    stages: [
      {
        id: 'pp001-stage-001',
        order: 1,
        title: 'Chuẩn bị đất',
        description: 'Làm đất, bón phân lót, san phẳng mặt ruộng. Ngâm ruộng 3-5 ngày.',
        status: 'done',
        dateFrom: '2026-02-15',
        dateTo: '2026-02-22',
      },
      {
        id: 'pp001-stage-002',
        order: 2,
        title: 'Gieo sạ',
        description: 'Gieo hạt giống, mật độ 120kg/ha.',
        status: 'done',
        dateFrom: '2026-02-23',
        dateTo: '2026-02-25',
      },
      {
        id: 'pp001-stage-003',
        order: 3,
        title: 'Chăm sóc đẻ nhánh',
        description: 'Bón phân thúc, phun thuốc trừ sâu.',
        status: 'inProgress',
        dateFrom: '2026-03-10',
        dateTo: '2026-04-05',
      },
      {
        id: 'pp001-stage-004',
        order: 4,
        title: 'Làm đòng - Trổ',
        description: 'Bón phân lần 2, phòng bệnh đạo ôn.',
        status: 'notStarted',
        dateFrom: '2026-04-06',
        dateTo: '2026-05-10',
      },
      {
        id: 'pp001-stage-005',
        order: 5,
        title: 'Thu hoạch',
        description: 'Thu hoạch khi 85-90% hạt chín vàng.',
        status: 'notStarted',
        dateFrom: '2026-05-25',
        dateTo: '2026-06-05',
      },
    ],
  },
  {
    id: 'PP-002',
    name: 'Cà chua Cherry 2026 - Nhà lưới 1',
    crop: 'Cà chua',
    category: 'Rau củ quả',
    specificCrop: 'Cà chua Cherry F1',
    area: 'Nhà lưới số 1',
    supervisor: {
      name: 'Trần Thị Bình',
      avatarColor: 'bg-green-500',
    },
    supervisorId: 'user-002',
    startDate: '2026-03-01',
    expectedStartDate: '2026-03-01',
    isPlanned: false,
    status: true,
    createdAt: '2026-02-10',
    stages: [
      {
        id: 'pp002-stage-001',
        order: 1,
        title: 'Ươm cây giống',
        description: 'Ươm hạt trong khay xốp 50 lỗ.',
        status: 'done',
        dateFrom: '2026-03-01',
        dateTo: '2026-03-28',
      },
      {
        id: 'pp002-stage-002',
        order: 2,
        title: 'Trồng',
        description: 'Trồng cây con vào luống đã chuẩn bị.',
        status: 'done',
        dateFrom: '2026-03-29',
        dateTo: '2026-04-01',
      },
      {
        id: 'pp002-stage-003',
        order: 3,
        title: 'Chăm sóc cây non',
        description: 'Tưới nhỏ giọt, phun phân bón lá.',
        status: 'inProgress',
        dateFrom: '2026-04-02',
        dateTo: '2026-04-25',
      },
      {
        id: 'pp002-stage-004',
        order: 4,
        title: 'Ra hoa - đậu quả',
        description: 'Tỉa cành, phun hormone.',
        status: 'notStarted',
        dateFrom: '2026-04-26',
        dateTo: '2026-05-30',
      },
      {
        id: 'pp002-stage-005',
        order: 5,
        title: 'Thu hoạch',
        description: 'Thu hái khi quả chín 70-80%.',
        status: 'notStarted',
        dateFrom: '2026-06-01',
        dateTo: '2026-07-15',
      },
    ],
  },
  {
    id: 'PP-003',
    name: 'Dưa lưới Nhật Bản - Nhà màng 2',
    crop: 'Dưa lưới',
    category: 'Rau củ quả',
    specificCrop: 'Dưa lưới Nhật F1',
    area: 'Nhà màng số 2',
    supervisor: {
      name: 'Lê Minh Chiến',
      avatarColor: 'bg-orange-500',
    },
    supervisorId: 'user-003',
    startDate: '2026-04-10',
    expectedStartDate: '2026-04-10',
    isPlanned: false,
    status: true,
    createdAt: '2026-03-15',
    stages: [
      {
        id: 'pp003-stage-001',
        order: 1,
        title: 'Ươm giống',
        description: 'Ươm trong cốc giấy 20-25 ngày.',
        status: 'done',
        dateFrom: '2026-04-10',
        dateTo: '2026-05-02',
      },
      {
        id: 'pp003-stage-002',
        order: 2,
        title: 'Trồng',
        description: 'Trồng cây con có 3-4 lá thật.',
        status: 'inProgress',
        dateFrom: '2026-05-03',
        dateTo: '2026-05-05',
      },
      {
        id: 'pp003-stage-003',
        order: 3,
        title: 'Dẫn dây và tạo tán',
        description: 'Dẫn cây lên giàn, tỉa ngọn.',
        status: 'notStarted',
        dateFrom: '2026-05-06',
        dateTo: '2026-05-25',
      },
      {
        id: 'pp003-stage-004',
        order: 4,
        title: 'Thụ phấn và chăm sóc quả',
        description: 'Thụ phấn nhân tạo, để 1 quả/nhánh.',
        status: 'notStarted',
        dateFrom: '2026-05-26',
        dateTo: '2026-06-20',
      },
      {
        id: 'pp003-stage-005',
        order: 5,
        title: 'Thu hoạch',
        description: 'Thu hoạch sau 45-50 ngày thụ phấn.',
        status: 'notStarted',
        dateFrom: '2026-06-21',
        dateTo: '2026-06-30',
      },
    ],
  },
  {
    id: 'PP-004',
    name: 'Xà lách thủy canh - Hệ thống NFT 1',
    crop: 'Xà lách',
    category: 'Rau ăn lá',
    specificCrop: 'Xà lách xoăn xanh',
    area: 'Nhà kính thủy canh 1',
    supervisor: {
      name: 'Phạm Thị Dung',
      avatarColor: 'bg-teal-500',
    },
    supervisorId: 'user-004',
    startDate: '2026-06-01',
    expectedStartDate: '2026-06-01',
    isPlanned: false,
    status: true,
    createdAt: '2026-05-20',
    stages: [
      {
        id: 'pp004-stage-001',
        order: 1,
        title: 'Ươm hạt',
        description: 'Ươm trong mút xốp 10-12 ngày.',
        status: 'done',
        dateFrom: '2026-06-01',
        dateTo: '2026-06-12',
      },
      {
        id: 'pp004-stage-002',
        order: 2,
        title: 'Chuyển sang bể thủy canh',
        description: 'Đặt cây vào khay NFT, EC 1.2-1.5.',
        status: 'inProgress',
        dateFrom: '2026-06-13',
        dateTo: '2026-06-15',
      },
      {
        id: 'pp004-stage-003',
        order: 3,
        title: 'Chăm sóc',
        description: 'Kiểm tra EC, pH hàng ngày.',
        status: 'notStarted',
        dateFrom: '2026-06-16',
        dateTo: '2026-07-02',
      },
      {
        id: 'pp004-stage-004',
        order: 4,
        title: 'Thu hoạch',
        description: 'Thu hoạch sau 30-35 ngày.',
        status: 'notStarted',
        dateFrom: '2026-07-03',
        dateTo: '2026-07-10',
      },
    ],
  },
  {
    id: 'PP-005',
    name: 'Dâu tây Đà Lạt - Khu B',
    crop: 'Dâu tây',
    category: 'Cây ăn quả',
    specificCrop: 'Dâu tây Đà Lạt',
    area: 'Khu B - Vùng cao',
    supervisor: {
      name: 'Hoàng Văn Em',
      avatarColor: 'bg-pink-500',
    },
    supervisorId: 'user-005',
    startDate: '2026-08-15',
    expectedStartDate: '2026-08-15',
    isPlanned: true,
    status: true,
    createdAt: '2026-07-01',
    stages: [
      {
        id: 'pp005-stage-001',
        order: 1,
        title: 'Chọn giống và xử lý',
        description: 'Chọn cây giống tơ khỏe mạnh.',
        status: 'notStarted',
      },
      {
        id: 'pp005-stage-002',
        order: 2,
        title: 'Trồng trên giá thể',
        description: 'Trồng vào bầu xốp với giá thể.',
        status: 'notStarted',
      },
      {
        id: 'pp005-stage-003',
        order: 3,
        title: 'Giai đoạn phục hồi',
        description: 'Tưới đủ ẩm, che nắng 7-10 ngày.',
        status: 'notStarted',
      },
      {
        id: 'pp005-stage-004',
        order: 4,
        title: 'Ra hoa và đậu quả',
        description: 'Tỉa bỏ hoa đợt 1, bón phân.',
        status: 'notStarted',
      },
      {
        id: 'pp005-stage-005',
        order: 5,
        title: 'Thu hoạch',
        description: 'Thu khi quả chín đỏ 80%.',
        status: 'notStarted',
      },
    ],
  },
  {
    id: 'PP-006',
    name: 'Ớt hiểm Tây Ninh - Khu C',
    crop: 'Ớt',
    category: 'Rau gia vị',
    specificCrop: 'Ớt hiểm Tây Ninh',
    area: 'Khu C - Đất đồi',
    supervisor: {
      name: 'Võ Thị Phương',
      avatarColor: 'bg-red-500',
    },
    supervisorId: 'user-006',
    startDate: '2026-07-01',
    expectedStartDate: '2026-07-01',
    isPlanned: false,
    status: true,
    createdAt: '2026-06-10',
    stages: [
      {
        id: 'pp006-stage-001',
        order: 1,
        title: 'Ươm cây giống',
        description: 'Ươm 30-35 ngày.',
        status: 'done',
        dateFrom: '2026-07-01',
        dateTo: '2026-08-05',
      },
      {
        id: 'pp006-stage-002',
        order: 2,
        title: 'Trồng và bón lót',
        description: 'Trồng trên luống cao.',
        status: 'notStarted',
        dateFrom: '2026-08-06',
        dateTo: '2026-08-08',
      },
      {
        id: 'pp006-stage-003',
        order: 3,
        title: 'Chăm sóc cây non',
        description: 'Cắm cọc, tỉa cành.',
        status: 'notStarted',
      },
      {
        id: 'pp006-stage-004',
        order: 4,
        title: 'Ra hoa - đậu quả',
        description: 'Tưới đủ ẩm, bón phân.',
        status: 'notStarted',
      },
      {
        id: 'pp006-stage-005',
        order: 5,
        title: 'Thu hoạch',
        description: 'Hái khi quả chuyển màu đỏ.',
        status: 'notStarted',
      },
    ],
  },
  {
    id: 'PP-007',
    name: 'Su hào hữu cơ - Khu D',
    crop: 'Su hào',
    category: 'Rau củ',
    specificCrop: 'Su hào trắng',
    area: 'Khu D - Đất phù sa',
    supervisor: {
      name: 'Đỗ Văn Giang',
      avatarColor: 'bg-purple-500',
    },
    supervisorId: 'user-007',
    startDate: '2026-09-01',
    expectedStartDate: '2026-09-01',
    isPlanned: true,
    status: true,
    createdAt: '2026-08-01',
    stages: [
      {
        id: 'pp007-stage-001',
        order: 1,
        title: 'Chuẩn bị đất',
        description: 'Bón phân hữu cơ 2-3 tấn/ha.',
        status: 'notStarted',
      },
      {
        id: 'pp007-stage-002',
        order: 2,
        title: 'Gieo hạt',
        description: 'Gieo trực tiếp, khoảng cách 30x30cm.',
        status: 'notStarted',
      },
      {
        id: 'pp007-stage-003',
        order: 3,
        title: 'Chăm sóc',
        description: 'Tưới đủ ẩm, bón phân hữu cơ lỏng.',
        status: 'notStarted',
      },
      {
        id: 'pp007-stage-004',
        order: 4,
        title: 'Thu hoạch',
        description: 'Thu sau 60-70 ngày.',
        status: 'notStarted',
      },
    ],
  },
  {
    id: 'PP-008',
    name: 'Bắp cải xanh - Khu E',
    crop: 'Bắp cải',
    category: 'Rau ăn lá',
    specificCrop: 'Bắp cải xanh ngọt',
    area: 'Khu E - Đất cao',
    supervisor: {
      name: 'Bùi Thị Hoa',
      avatarColor: 'bg-green-500',
    },
    supervisorId: 'user-008',
    startDate: '2026-10-01',
    expectedStartDate: '2026-10-01',
    isPlanned: true,
    status: true,
    createdAt: '2026-09-01',
    stages: [
      {
        id: 'pp008-stage-001',
        order: 1,
        title: 'Ươm cây',
        description: 'Ươm 20-25 ngày.',
        status: 'notStarted',
      },
      {
        id: 'pp008-stage-002',
        order: 2,
        title: 'Làm đất và trồng',
        description: 'Làm luống cao, bón lót.',
        status: 'notStarted',
      },
      {
        id: 'pp008-stage-003',
        order: 3,
        title: 'Chăm sóc cây non',
        description: 'Tưới nhẹ, bón phân thúc.',
        status: 'notStarted',
      },
      {
        id: 'pp008-stage-004',
        order: 4,
        title: 'Cuốn cải',
        description: 'Bón phân kali.',
        status: 'notStarted',
      },
      {
        id: 'pp008-stage-005',
        order: 5,
        title: 'Thu hoạch',
        description: 'Thu sau 75-90 ngày.',
        status: 'notStarted',
      },
    ],
  },
  {
    id: 'PP-009',
    name: 'Dưa hấu không hạt - Khu F',
    crop: 'Dưa hấu',
    category: 'Cây ăn quả',
    specificCrop: 'Dưa hấu không hạt F1',
    area: 'Khu F - Đồng cát',
    supervisor: {
      name: 'Trương Văn Ích',
    },
    supervisorId: 'user-009',
    startDate: '2026-11-15',
    expectedStartDate: '2026-11-15',
    isPlanned: true,
    status: true,
    createdAt: '2026-10-15',
    stages: [
      {
        id: 'pp009-stage-001',
        order: 1,
        title: 'Gieo hạt trực tiếp',
        description: 'Gieo hạt vào hố đã chuẩn bị.',
        status: 'notStarted',
      },
      {
        id: 'pp009-stage-002',
        order: 2,
        title: 'Chăm sóc cây non',
        description: 'Tưới, bón phân, phun thuốc.',
        status: 'notStarted',
      },
      {
        id: 'pp009-stage-003',
        order: 3,
        title: 'Ra hoa - đậu quả',
        description: 'Thụ phấn nhân tạo, chọn quả.',
        status: 'notStarted',
      },
      {
        id: 'pp009-stage-004',
        order: 4,
        title: 'Phát triển quả',
        description: 'Bón phân kali, lót rơm dưới quả.',
        status: 'notStarted',
      },
      {
        id: 'pp009-stage-005',
        order: 5,
        title: 'Thu hoạch',
        description: 'Thu sau 70-80 ngày trồng.',
        status: 'notStarted',
      },
    ],
  },
  {
    id: 'PP-010',
    name: 'Bí đỏ dinh dưỡng - Khu G',
    crop: 'Bí đỏ',
    category: 'Rau củ quả',
    specificCrop: 'Bí đỏ Nhật Bản',
    area: 'Khu G - Vườn rộng',
    supervisor: {
      name: 'Ngô Thị Kim',
      avatarColor: 'bg-amber-500',
    },
    supervisorId: 'user-010',
    startDate: '2026-05-20',
    expectedStartDate: '2026-05-20',
    isPlanned: false,
    status: true,
    createdAt: '2026-04-25',
    stages: [
      {
        id: 'pp010-stage-001',
        order: 1,
        title: 'Gieo hạt',
        description: 'Gieo trực tiếp hoặc ươm cây con.',
        status: 'done',
        dateFrom: '2026-05-20',
        dateTo: '2026-05-22',
      },
      {
        id: 'pp010-stage-002',
        order: 2,
        title: 'Chăm sóc cây dây',
        description: 'Tưới, bón phân, dẫn cây.',
        status: 'done',
        dateFrom: '2026-05-23',
        dateTo: '2026-06-15',
      },
      {
        id: 'pp010-stage-003',
        order: 3,
        title: 'Ra hoa - đậu quả',
        description: 'Thụ phấn, để 2-3 quả/cây.',
        status: 'inProgress',
        dateFrom: '2026-06-16',
        dateTo: '2026-07-10',
      },
      {
        id: 'pp010-stage-004',
        order: 4,
        title: 'Thu hoạch',
        description: 'Thu sau 90-110 ngày.',
        status: 'notStarted',
        dateFrom: '2026-08-15',
        dateTo: '2026-08-25',
      },
    ],
  },
  {
    id: 'PP-011',
    name: 'Cải thìa xanh - Nhà lưới 3',
    crop: 'Cải thìa',
    category: 'Rau ăn lá',
    specificCrop: 'Cải thìa xanh ngọt',
    area: 'Nhà lưới số 3',
    supervisor: {
      name: 'Lý Văn Long',
      avatarColor: 'bg-lime-500',
    },
    supervisorId: 'user-011',
    startDate: '2026-06-15',
    expectedStartDate: '2026-06-15',
    isPlanned: false,
    status: true,
    createdAt: '2026-06-01',
    stages: [
      {
        id: 'pp011-stage-001',
        order: 1,
        title: 'Gieo hạt',
        description: 'Gieo trực tiếp trên luống.',
        status: 'done',
        dateFrom: '2026-06-15',
        dateTo: '2026-06-16',
      },
      {
        id: 'pp011-stage-002',
        order: 2,
        title: 'Chăm sóc',
        description: 'Tưới 2 lần/ngày, bón phân.',
        status: 'inProgress',
        dateFrom: '2026-06-17',
        dateTo: '2026-07-08',
      },
      {
        id: 'pp011-stage-003',
        order: 3,
        title: 'Thu hoạch',
        description: 'Thu sau 25-30 ngày.',
        status: 'notStarted',
        dateFrom: '2026-07-10',
        dateTo: '2026-07-15',
      },
    ],
  },
  {
    id: 'PP-012',
    name: 'Kế hoạch Hành tím 2026',
    crop: 'Hành',
    category: 'Rau gia vị',
    specificCrop: 'Hành tím Lý Sơn',
    area: 'Khu H - Đất cát ven biển',
    supervisor: {
      name: 'Mai Thị Ngọc',
      avatarColor: 'bg-violet-500',
    },
    supervisorId: 'user-012',
    startDate: '2026-12-01',
    expectedStartDate: '2026-12-01',
    isPlanned: true,
    status: true,
    createdAt: '2026-11-01',
    stages: [
      {
        id: 'pp012-stage-001',
        order: 1,
        title: 'Chuẩn bị và trồng',
        description: 'Chọn củ giống, trồng với khoảng cách 15x20cm.',
        status: 'notStarted',
      },
      {
        id: 'pp012-stage-002',
        order: 2,
        title: 'Chăm sóc',
        description: 'Tưới vừa phải, bón phân 2-3 lần.',
        status: 'notStarted',
      },
      {
        id: 'pp012-stage-003',
        order: 3,
        title: 'Thu hoạch',
        description: 'Thu sau 90-100 ngày khi ngọn héo.',
        status: 'notStarted',
      },
    ],
  },
]

// Mock helper functions
export const getMockProductionPlans = (params = {}) => {
  let filtered = [...MOCK_PRODUCTION_PLANS]

  // Filter by search
  if (params.SearchKeyword) {
    const keyword = params.SearchKeyword.toLowerCase()
    filtered = filtered.filter(
      (item) =>
        item.name.toLowerCase().includes(keyword) ||
        item.id.toLowerCase().includes(keyword) ||
        item.crop?.toLowerCase().includes(keyword) ||
        item.area?.toLowerCase().includes(keyword)
    )
  }

  // Filter by status
  if (params.Status !== undefined && params.Status !== 'all') {
    filtered = filtered.filter((item) => item.status === params.Status)
  }

  const pageIndex = params.PageIndex || 1
  const pageSize = params.PageSize || 10
  const startIndex = (pageIndex - 1) * pageSize
  const endIndex = startIndex + pageSize

  return {
    success: true,
    data: {
      items: filtered.slice(startIndex, endIndex),
      totalItems: filtered.length,
      pageIndex,
      pageSize,
    },
  }
}

export const getMockProductionPlanById = (id) => {
  const plan = MOCK_PRODUCTION_PLANS.find((p) => p.id === id)
  if (plan) {
    return {
      success: true,
      data: plan,
    }
  }
  return {
    success: false,
    message: 'Không tìm thấy kế hoạch sản xuất',
  }
}
