const geomanVi = {
  tooltips: {
    placeMarker: 'Nhấp để đặt điểm đánh dấu',
    placeMarkerTouch: 'Chạm bản đồ để đặt điểm đánh dấu',
    firstVertex: 'Nhấp để đặt đỉnh đầu tiên',
    continueLine: 'Nhấp để tiếp tục vẽ',
    finishLine: 'Nhấp vào điểm đánh dấu có sẵn để hoàn tất',
    finishPoly: 'Nhấp vào điểm đánh dấu đầu tiên để hoàn tất',
    finishRect: 'Nhấp để hoàn tất',
    startCircle: 'Nhấp để đặt tâm hình tròn',
    finishCircle: 'Nhấp để hoàn tất hình tròn',
    placeCircleMarker: 'Nhấp để đặt điểm đánh dấu hình tròn',
    placeText: 'Nhấp để đặt văn bản',
    selectFirstLayerFor: 'Chọn lớp đầu tiên cho {action}',
    selectSecondLayerFor: 'Chọn lớp thứ hai cho {action}',
  },
  actions: {
    finish: 'Hoàn tất',
    cancel: 'Hủy',
    removeLastVertex: 'Xóa đỉnh cuối',
  },
  buttonTitles: {
    drawMarkerButton: 'Vẽ điểm đánh dấu',
    drawPolyButton: 'Vẽ đa giác',
    drawLineButton: 'Vẽ đường',
    drawCircleButton: 'Vẽ hình tròn',
    drawRectButton: 'Vẽ hình chữ nhật',
    editButton: 'Chỉnh sửa lớp',
    dragButton: 'Kéo lớp',
    cutButton: 'Cắt lớp',
    deleteButton: 'Xóa lớp',
    drawCircleMarkerButton: 'Vẽ điểm đánh dấu hình tròn',
    snappingButton: 'Bắt dính điểm với lớp và đỉnh khác',
    pinningButton: 'Ghim các đỉnh chung lại với nhau',
    rotateButton: 'Xoay lớp',
    drawTextButton: 'Vẽ văn bản',
    scaleButton: 'Thu phóng lớp',
    autoTracingButton: 'Tự động truy vết đường',
    snapGuidesButton: 'Hiện đường căn chỉnh',
    unionButton: 'Gộp lớp',
    differenceButton: 'Trừ lớp',
  },
  measurements: {
    totalLength: 'Chiều dài',
    segmentLength: 'Chiều dài đoạn',
    area: 'Diện tích',
    radius: 'Bán kính',
    perimeter: 'Chu vi',
    height: 'Chiều cao',
    width: 'Chiều rộng',
    coordinates: 'Vị trí',
    coordinatesMarker: 'Vị trí điểm đánh dấu',
  },
}

export default geomanVi
